// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "device-mocks/android.mdx": () => import("../content/docs/device-mocks/android.mdx?collection=docs"), "device-mocks/browser.mdx": () => import("../content/docs/device-mocks/browser.mdx?collection=docs"), "device-mocks/iphone.mdx": () => import("../content/docs/device-mocks/iphone.mdx?collection=docs"), "device-mocks/laptop.mdx": () => import("../content/docs/device-mocks/laptop.mdx?collection=docs"), "components/activity-dropdown.mdx": () => import("../content/docs/components/activity-dropdown.mdx?collection=docs"), "components/ai-prompt-box-glassmorphism.mdx": () => import("../content/docs/components/ai-prompt-box-glassmorphism.mdx?collection=docs"), "components/ai-prompt-box-neomorphism.mdx": () => import("../content/docs/components/ai-prompt-box-neomorphism.mdx?collection=docs"), "components/aurora-button.mdx": () => import("../content/docs/components/aurora-button.mdx?collection=docs"), "components/bento-grid.mdx": () => import("../content/docs/components/bento-grid.mdx?collection=docs"), "components/glass-dock.mdx": () => import("../content/docs/components/glass-dock.mdx?collection=docs"), "components/light-trail-badge.mdx": () => import("../content/docs/components/light-trail-badge.mdx?collection=docs"), "components/like-button.mdx": () => import("../content/docs/components/like-button.mdx?collection=docs"), "components/magnetic-pit-slider.mdx": () => import("../content/docs/components/magnetic-pit-slider.mdx?collection=docs"), "components/navbar.mdx": () => import("../content/docs/components/navbar.mdx?collection=docs"), "components/social-proof.mdx": () => import("../content/docs/components/social-proof.mdx?collection=docs"), "backgrounds/animated-grid-background.mdx": () => import("../content/docs/backgrounds/animated-grid-background.mdx?collection=docs"), "backgrounds/wavy-grid-background.mdx": () => import("../content/docs/backgrounds/wavy-grid-background.mdx?collection=docs"), "text/iconic-text.mdx": () => import("../content/docs/text/iconic-text.mdx?collection=docs"), "text/underline-heading.mdx": () => import("../content/docs/text/underline-heading.mdx?collection=docs"), }),
};
export default browserCollections;