import type { ComponentType, ReactNode } from "react";
import type { VisualKitEntry } from "@/components/previews/visual-kit-data";
import {
  AnimatedUnderlineText,
  AuroraWashField,
  BlurInText,
  BreatheScaleCard,
  BlinkCaretLine,
  ChromeGradientText,
  CinematicVignetteBreath,
  ConicBorderSpinnerPlate,
  ConicRainbowHalo,
  ConfettiSpeckles,
  CrossingLaserBeams,
  DashedEllipseOrbit,
  DiagonalShineBands,
  DiagonalStripeField,
  DotMatrixField,
  EchoPulseRings,
  FilmGrainOverlay,
  FrostedGlassTile,
  GentleFloatShell,
  GlowingInsetFrame,
  GlitchSkewText,
  HexLatticeField,
  IridescentSheenOverlay,
  MarqueeFadeStrip,
  MetaballFusionPair,
  MiniEqBars,
  MorphBlobField,
  NeonGlowText,
  NeonPulseFrame,
  NeonWireGrid,
  OrbClusterGlow,
  OrbitTrailDots,
  ParallaxStarsField,
  PastelMistWash,
  RadiantDotBadge,
  RetroScanlines,
  RippleGlassCard,
  RipplePoolSurface,
  ShimmerWashCard,
  SlowRotateDrift,
  SmokeWispWash,
  SoftMeshWash,
  SonarRippleWell,
  SparkleBadgeChip,
  SparkleDustField,
  SpotlightConeSweep,
  SplitHueText,
  SweepHighlightText,
  TechCornerBrackets,
  TiltHoverSurface,
} from "@/registry/senko-visual-effects";

/** Static map so every primitive is a real import (avoids empty previews with `import *` + dynamic keys). */
export type VisualKitComponentProps = {
  className?: string;
  children?: ReactNode;
  label?: string;
};

export const VISUAL_KIT_COMPONENT_MAP: Record<
  VisualKitEntry["component"],
  ComponentType<VisualKitComponentProps>
> = {
  AuroraWashField,
  DiagonalStripeField,
  DotMatrixField,
  HexLatticeField,
  FilmGrainOverlay,
  OrbClusterGlow,
  SoftMeshWash,
  RetroScanlines,
  SpotlightConeSweep,
  ConicRainbowHalo,
  ParallaxStarsField,
  MorphBlobField,
  NeonWireGrid,
  PastelMistWash,
  CinematicVignetteBreath,
  CrossingLaserBeams,
  RipplePoolSurface,
  SmokeWispWash,
  DiagonalShineBands,
  SparkleDustField,
  GlowingInsetFrame,
  ShimmerWashCard,
  ConicBorderSpinnerPlate,
  TechCornerBrackets,
  NeonPulseFrame,
  FrostedGlassTile,
  DashedEllipseOrbit,
  ConfettiSpeckles,
  IridescentSheenOverlay,
  RippleGlassCard,
  EchoPulseRings,
  GentleFloatShell,
  SlowRotateDrift,
  BreatheScaleCard,
  TiltHoverSurface,
  MarqueeFadeStrip,
  SparkleBadgeChip,
  RadiantDotBadge,
  MiniEqBars,
  BlinkCaretLine,
  ChromeGradientText,
  GlitchSkewText,
  BlurInText,
  SplitHueText,
  AnimatedUnderlineText,
  SweepHighlightText,
  NeonGlowText,
  OrbitTrailDots,
  SonarRippleWell,
  MetaballFusionPair,
};
